### ISSUE TITLE
urllib.error.URLError: <urlopen error unknown url type: https>

### ISSUE THREAD

**Issue by pp0229** [harvardnlp/botnet-detection#1]
Hi, the author, When I'm using this package, the following error has been bothering me :
```
**raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>**
```
but I can't sovle it, could you please give some advices? Thank you ~~

**Comment by jzhou316** [comment]
Hi there, I think this might have something to do with your particular Python or platform setups. I found the following resources that might be helpful:
https://stackoverflow.com/questions/27208131/urllib-cannot-read-https
https://stackoverflow.com/questions/28376506/urllib-https-request-urlopen-error-unknown-url-type-https
https://stackoverflow.com/questions/27115803/urllib-error-urlerror-urlopen-error-unknown-url-type-https

In particular, can you try a simple test like [this](https://stackoverflow.com/a/27208548) to see if it works and then try to work around it?

**Comment by pp0229** [comment]
Thank you sir , Combine the links you gave me：


first, I have tried a simple test and found it didn't work either,&nbsp;


then, I looked for the answer in the link you gave me and found the problem：The python I used is python3.7.7, in this case, when I import ssl, it failed. But in another environment which python=3.7.0, I can import ssl successfully.&nbsp;


So what I have done was just reinstall python, in this process, there were also some problems, but they were all solved smoothly.&nbsp;


Now, I can use the package happily!!&nbsp;&nbsp;I do appreciate&nbsp; your help !!









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jzhou316"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 晚上11:56
收件人:&nbsp;"harvardnlp/botnet-detection"<botnet-detection@noreply.github.com&gt;;
抄送:&nbsp;"佩佩"<1398470600@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [harvardnlp/botnet-detection] urllib.error.URLError: <urlopen error unknown url type: https&gt; (#1)





 
Hi there, I think this might have something to do with your particular Python or platform setups. I found the following resources that might be helpful:
 https://stackoverflow.com/questions/27208131/urllib-cannot-read-https
 https://stackoverflow.com/questions/28376506/urllib-https-request-urlopen-error-unknown-url-type-https
 https://stackoverflow.com/questions/27115803/urllib-error-urlerror-urlopen-error-unknown-url-type-https
 
In particular, can you try a simple test like this to see if it works and then try to work around it?

**Comment by jzhou316** [comment]
Great! Glad to hear that.
