### ISSUE TITLE
I think there is a mistake

### ISSUE THREAD

**Issue by whxuexi** [harvardnlp/botnet-detection#19]
In scatter_ of common.py, out (SRC, index, 0, out, dim_size, fill_value) has 6 parameters, but the display can only enter 2-5 parameters.

**Comment by jzhou316** [comment]
Hi, this is a package version issue. Can you check the previous discussion [here](https://github.com/harvardnlp/botnet-detection/issues/8#issuecomment-869620743) and see if it helps?

**Comment by TruongDuyLongPTIT** [comment]
You just delete fill_value paramater. It will work
