### ISSUE TITLE
Thank for your paper and repo.

### ISSUE THREAD

**Issue by TruongDuyLongPTIT** [harvardnlp/botnet-detection#20]
Thank for your paper and repo.
But i have an trouble.
When i run load data script. It have an error "no module deepdish".
It really hard to fix. Pls help me

**Comment by jzhou316** [comment]
Hi there, it is a third-party package (see instructions [here](https://github.com/uchicago-cs/deepdish)) and you have to install the package via `pip install deepdish`. Hope it will resolve the problem!

**Comment by TruongDuyLongPTIT** [comment]
> Xin chào, đây là gói của bên thứ ba (xem hướng dẫn [tại đây](https://github.com/uchicago-cs/deepdish) ) và bạn phải cài đặt gói qua `pip install deepdish`. Hy vọng nó sẽ giải quyết vấn đề!

Thank you. I solved it by conda.
