### ISSUE TITLE
Running the training scripts in Jupyter: Issues with arguments

### ISSUE THREAD

**Issue by helmoai** [harvardnlp/botnet-detection#8]
I translated part of the training script in `train_botnet.py` to jupyter notebook and while calling `train` with the parameters provided in the script, I get:

`TypeError: scatter_add() takes from 2 to 5 positional arguments but 6 were given`

This seems to happen during the forward pass in: `x = model(batch.x, batch.edge_index)` in `train` when `aggr = 'add'` but similar issue happens when `aggr = 'mean'` and error changes to `TypeError: scatter_mean() takes from 2 to 5 positional arguments but 6 were given` and in similar fashion for  `aggr = 'max'`

Any ideas why this happens?

**Comment by iamgroot42** [comment]
This is an issue with version-mismatch for [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter)

**Comment by helmoai** [comment]
> This is an issue with version-mismatch for [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter)

Thanks. Which version did you use?

**Comment by iamgroot42** [comment]
> > This is an issue with version-mismatch for [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter)
> 
> Thanks. Which version did you use?

2.0.7

**Comment by helmoai** [comment]
> > > This is an issue with version-mismatch for [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter)
> > 
> > 
> > Thanks. Which version did you use?
> 
> 2.0.7

That's exactly the same I have been using and the issue prevails. :O

**Comment by iamgroot42** [comment]
That's weird- I had the same bug and changing the version fixed this bug for me :/ I'm on PyTorch 1.7.1, if that helps

**Comment by jzhou316** [comment]
Hi @helmoai , sorry for the trouble. It seem the line causing the issue is https://github.com/harvardnlp/botnet-detection/blob/5ae24416134d66574b31037b7c22ca083510b6f5/botdet/models_pyg/common.py#L56, where the [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter/tree/1.4.0) has made some changes of the number of arguments starting the 2.x versions. I used version 1.3.1 before and it seems 1.4.0 also maintained the same code structure. Can you try these earlier versions and see if any of them work?

**Comment by helmoai** [comment]
Hi @jzhou316 , thanks for your input. Mind if I ask which PyTorch version and OS did you use? And whether did you use Cuda versions of torch and related libraries? The version 1.3.1 won't work with newer PyTorch with cuda, atleast on windows. So, I wonder what was the setup you had when you worked on this project. Thanks.

**Comment by jzhou316** [comment]
Hi @helmoai , sorry I did not notice that older versions of torch-scatter are not compatible with later PyTorch versions.  Below I extracted my development environment:

[OS] I'm using a shared Linux system on a school computing cluster
```
NAME="CentOS Linux"
VERSION="7 (Core)"
``` 

[env management] I'm using conda, everything is installed inside of a conda environment. For PyTorch and related libraries, I used conda to install unless the package should be installed with pip. The versions of my main packages (along with installation commands I used) are
```
python: 3.7.2    (conda install python=3.7)
pytorch:  1.2.0   py3.7_cuda10.0.130_cudnn7.6.2_0    (conda install pytorch==1.2.0 cudatoolkit=10.0 -c pytorch) (notice of your cuda version)
torch-scatter:  1.3.1   (pip install torch-scatter=1.3.1)
```
Maybe try to install these main packages inside a new conda environment and then do `python setup.py install` for the main repo and other small dependencies?

**Comment by mane2shar** [comment]
I think cuda supports python 3.6.x as of now. So please check in that context.

**Comment by helmoai** [comment]
@jzhou316 Thanks for these inputs. I can say that it might make sense to only reproduce it on Linux, as I tried with windows without much success (mainly due to old torch-* libraries that won't compile at all on windows, only the new ones. 

Will see what I can do. But just to close this issue, could you tell more or less how long did it take to training the model, say, running it with the bash script as it is? And how much VRAM did your GPU have? I am trying to estimate how long will I have to run my computer in the event I manage to reproduce it as it is. Thanks in advance.

**Comment by mane2shar** [comment]
Intel i7 10th gen , 16 GB RAM, Nvidia GeForce 6 GB ..... It took hardly 5 mins while I got stuck .... I tried almost 2 days to resolve with different versions .... None of could help on windows.

**Comment by helmoai** [comment]
Thanks @mane2shar

**Comment by mane2shar** [comment]
Would it run on latest ubuntu ? If yes I can install alongside with windows then

**Comment by helmoai** [comment]
> Would it run on latest ubuntu ? If yes I can install alongside with windows then

I wanted to try through WSL as I run Ubuntu that way. But I don't want to change to Windows Preview in order to have WSL with GPU support. But might consider running Ubuntu either as dual boot or on a separate external hard drive.

**Comment by mane2shar** [comment]
Ok. Thank you. I will update you.

**Comment by jzhou316** [comment]
@helmoai sorry to hear that. For training time with the script as-is in my environment, one epoch takes about 1.5 mins - 2 mins, and 50 epochs (max specified in the training script, although early stopping is enabled and you can change the setup too) take about 1.5 hours. My cluster GPU has 12G VRAM (TITAN X (Pascal)) and the CPU has about 120G memory (loading the whole data into memory takes about 25G, but with the [`in_memory = False`](https://github.com/harvardnlp/botnet-detection/blob/290e7cc563584038d2dd2eea7d8630b76927a5c1/train_botnet.py#L24) flag that can be avoided but would slightly slow down training a little bit). Training takes about 3G VRAM on my GPU.

(also @mane2shar) For running Linux commands within windows, I am using [git bash](https://git-scm.com/downloads) mostly and maybe you could give it a try. I had a pytorch1.3 (cpu-only since my windows computer does not have GPU) installed within a conda environment similar to how I did with Linux. So I am curious is the issue mostly about GPU support on windows? Or the torch-scatter package? Other solutions might be using a Linux with PyTorch docker image (but I'm not sure about the [GPU support with nvidia](https://stackoverflow.com/questions/49589229/is-gpu-pass-through-possible-with-docker-for-windows)), or trying to use Google colab where free GPUs are accessible.

**Comment by helmoai** [comment]
@jzhou316 thanks. I managed to run it. I kept the torch_scatter 2.07 and recent pytorch but modified your script `common.py` in **scatter_()** by removing the `fill_value`. That way it worked. Though might not be 1 to 1 reproducible that way. But I was curious to get the code to run then will check the results and play a bit more with the parameters and/or function arguments. 

As for in_memory = True, it keeps on saying that PyTables isn't installed. Maybe windows issue because it was installed. I did uninstall and install multiple times using pip and then using conda, and still kept on showing that message. That is also true if running the code with bash script on windows. Haven't tested on Linux.

The training takes about 1 hour for me, I have NVIDIA RTX 3080 (16 GB VRAM) and 64 GB RAM). Graphics is about the same as you about 3-4 is used during training.

**Comment by jzhou316** [comment]
@helmoai Thanks for the update! Yeah that might be the right way to go and more convenient (I might update the code for newer versions of `torch_scatter` based on your feedback here as well). 

For the PyTables issue, I think maybe you can test the following code to debug (which is the part to load the whole hdf5 file into memory)
```
import deepdish as dd
data = dd.io.load('data/botnet/processed/chord_train.hdf5')
```
(assuming the data is stored at data/botnet/processed/chord_train.hdf5).

**Comment by helmoai** [comment]
@jzhou316 that's true. Might be related to environment variable issue. Will check it out, thanks again.

**Comment by mane2shar** [comment]
> @helmoai sorry to hear that. For training time with the script as-is in my environment, one epoch takes about 1.5 mins - 2 mins, and 50 epochs (max specified in the training script, although early stopping is enabled and you can change the setup too) take about 1.5 hours. My cluster GPU has 12G VRAM (TITAN X (Pascal)) and the CPU has about 120G memory (loading the whole data into memory takes about 25G, but with the [`in_memory = False`](https://github.com/harvardnlp/botnet-detection/blob/290e7cc563584038d2dd2eea7d8630b76927a5c1/train_botnet.py#L24) flag that can be avoided but would slightly slow down training a little bit). Training takes about 3G VRAM on my GPU.
> 
> (also @mane2shar) For running Linux commands within windows, I am using [git bash](https://git-scm.com/downloads) mostly and maybe you could give it a try. I had a pytorch1.3 (cpu-only since my windows computer does not have GPU) installed within a conda environment similar to how I did with Linux. So I am curious is the issue mostly about GPU support on windows? Or the torch-scatter package? Other solutions might be using a Linux with PyTorch docker image (but I'm not sure about the [GPU support with nvidia](https://stackoverflow.com/questions/49589229/is-gpu-pass-through-possible-with-docker-for-windows)), or trying to use Google colab where free GPUs are accessible.

Should I execute the project within MinW with cpu only? Would it work then?

**Comment by mane2shar** [comment]
Can you please attach here pip freeze? That would really help, so that I can install packages easily in virtualenv.

**Comment by helmoai** [comment]
> Can you please attach here pip freeze? That would really help, so that I can install packages easily in virtualenv.

Hello, sure, but I don't know if that will be helpful. I use miniconda to manage the environment and some libraries were installed with conda and some with pip, so will share both here:

[requirements.txt](https://gist.github.com/helmoai/35b99887e9d1d19335de419ec8df0fd2)

[environment.yml](https://gist.github.com/helmoai/faf047935744fbae3534c88514118e9a)

**Comment by mane2shar** [comment]
> > Can you please attach here pip freeze? That would really help, so that I can install packages easily in virtualenv.
> 
> Hello, I don't know if that will be helpful. I use miniconda to manage the environment and some libraries were installed with conda and some with pip. If you use the [environment.yml](https://gist.github.com/helmoai/faf047935744fbae3534c88514118e9a) and a [conda](https://docs.conda.io/en/latest/miniconda.html) environment, it might work, but will share both here:
> 
> [requirements.txt](https://gist.github.com/helmoai/35b99887e9d1d19335de419ec8df0fd2)
> 
> [environment.yml](https://gist.github.com/helmoai/faf047935744fbae3534c88514118e9a)

Thank you so much
